"""initial schema

Revision ID: 9de308288812
Revises: 
Create Date: 2026-09-11 13:22:54.785134
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '9de308288812'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'version', name='uq_content_version')
    )
    op.create_table('principals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quota_counters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', 'window_start', name='uq_quota_window')
    )
    op.create_table('assessment_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.String(length=64), nullable=False),
    sa.Column('form', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'idempotency_key', name='uq_assessment_idempotency')
    )
    op.create_index(op.f('ix_assessment_attempts_principal_id'), 'assessment_attempts', ['principal_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_principal_id'), 'conversations', ['principal_id'], unique=False)
    op.create_table('delivered_hints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'task_id', 'level', name='uq_hint_owner_level')
    )
    op.create_index(op.f('ix_delivered_hints_principal_id'), 'delivered_hints', ['principal_id'], unique=False)
    op.create_table('guest_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_guest_sessions_principal_id'), 'guest_sessions', ['principal_id'], unique=False)
    op.create_table('preferences',
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('principal_id')
    )
    op.create_table('skill_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('item_family', sa.String(length=64), nullable=False),
    sa.Column('source_kind', sa.String(length=24), nullable=False),
    sa.Column('source_id', sa.String(length=96), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'skill_id', 'source_kind', 'source_id', name='uq_evidence_source')
    )
    op.create_index('ix_evidence_owner_skill', 'skill_evidence', ['principal_id', 'skill_id'], unique=False)
    op.create_index(op.f('ix_skill_evidence_principal_id'), 'skill_evidence', ['principal_id'], unique=False)
    op.create_table('topic_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('completed_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'topic_id', name='uq_topic_progress_owner')
    )
    op.create_index(op.f('ix_topic_progress_principal_id'), 'topic_progress', ['principal_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'topic_id', 'kind', name='uq_workspace_owner_topic')
    )
    op.create_index(op.f('ix_workspaces_principal_id'), 'workspaces', ['principal_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rubric_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_index(op.f('ix_evaluations_principal_id'), 'evaluations', ['principal_id'], unique=False)
    op.create_table('revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('circuit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('circuit_schema_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'ordinal', name='uq_revision_ordinal')
    )
    op.create_index(op.f('ix_revisions_principal_id'), 'revisions', ['principal_id'], unique=False)
    op.create_index(op.f('ix_revisions_workspace_id'), 'revisions', ['workspace_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=48), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_principal_id'), 'runs', ['principal_id'], unique=False)
    op.create_index(op.f('ix_runs_revision_id'), 'runs', ['revision_id'], unique=False)
    op.create_table('preview_encounters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('algorithm_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'algorithm_id', name='uq_preview_owner')
    )
    op.create_index(op.f('ix_preview_encounters_principal_id'), 'preview_encounters', ['principal_id'], unique=False)
    op.create_table('task_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=96), nullable=False),
    sa.Column('content_version', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('submission', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('assisted', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id', 'idempotency_key', name='uq_task_attempt_idempotency')
    )
    op.create_index('ix_task_attempt_owner_task', 'task_attempts', ['principal_id', 'task_id'], unique=False)
    op.create_index(op.f('ix_task_attempts_principal_id'), 'task_attempts', ['principal_id'], unique=False)
    op.create_table('tutor_turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('intent', sa.String(length=16), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('passage_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('followup_question', sa.Text(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('run_step', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=True),
    sa.Column('provider_model', sa.String(length=96), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('source_label', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_turns_conversation_id'), 'tutor_turns', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tutor_turns_principal_id'), 'tutor_turns', ['principal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_turns_principal_id'), table_name='tutor_turns')
    op.drop_index(op.f('ix_tutor_turns_conversation_id'), table_name='tutor_turns')
    op.drop_table('tutor_turns')
    op.drop_index(op.f('ix_task_attempts_principal_id'), table_name='task_attempts')
    op.drop_index('ix_task_attempt_owner_task', table_name='task_attempts')
    op.drop_table('task_attempts')
    op.drop_index(op.f('ix_preview_encounters_principal_id'), table_name='preview_encounters')
    op.drop_table('preview_encounters')
    op.drop_index(op.f('ix_runs_revision_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_principal_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_revisions_workspace_id'), table_name='revisions')
    op.drop_index(op.f('ix_revisions_principal_id'), table_name='revisions')
    op.drop_table('revisions')
    op.drop_index(op.f('ix_evaluations_principal_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_workspaces_principal_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_topic_progress_principal_id'), table_name='topic_progress')
    op.drop_table('topic_progress')
    op.drop_index(op.f('ix_skill_evidence_principal_id'), table_name='skill_evidence')
    op.drop_index('ix_evidence_owner_skill', table_name='skill_evidence')
    op.drop_table('skill_evidence')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_guest_sessions_principal_id'), table_name='guest_sessions')
    op.drop_table('guest_sessions')
    op.drop_index(op.f('ix_delivered_hints_principal_id'), table_name='delivered_hints')
    op.drop_table('delivered_hints')
    op.drop_index(op.f('ix_conversations_principal_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_assessment_attempts_principal_id'), table_name='assessment_attempts')
    op.drop_table('assessment_attempts')
    op.drop_table('quota_counters')
    op.drop_table('principals')
    op.drop_table('content_versions')
    # ### end Alembic commands ###
